{application,project2_bonus,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"project2_bonus"},
              {modules,['Elixir.GossipWorker','Elixir.PROJECT2BONUS',
                        'Elixir.ProjectSupervisor','Elixir.PushSumWorker',
                        'Elixir.WorkerManager']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
